### PR TITLE
No more auto vectorization

### LINKED ISSUE #36: TypeError in deprecation causing failure to load
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.1272 (2017-08-07 19:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 4e28870021* (0 days old master)
|__/                   |  x86_64-apple-darwin16.7.0

julia> Pkg.build("Rmath")
[a wave of BinDeps deprecations but no failure]

julia> using Rmath
INFO: Recompiling stale cache file /Users/alex/.julia/lib/v0.7/Rmath.ji for module Rmath.
ERROR: LoadError: TypeError: in @deprecate, in typeassert, expected Symbol, got Expr
Stacktrace:
 [1] include_relative(::Module, ::String) at ./loading.jl:464
 [2] include(::Module, ::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /Users/alex/.julia/v0.7/Rmath/src/Rmath.jl, in expression starting on line 235
ERROR: Failed to precompile Rmath to /Users/alex/.julia/lib/v0.7/Rmath.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:598
 [2] _require(::Symbol) at ./loading.jl:387
 [3] require(::Symbol) at ./loading.jl:318

julia> Pkg.status("Rmath")
 - Rmath                         0.2.0
```

### PR DESCRIPTION
**Pull request by andreasnoack**
They have been deprecated for almost a year so it should be okay remove them now.

Fixes #36

### CODE REVIEW

File: src/Rmath.jl [hunk 1]
```diff
@@ -52,116 +50,6 @@ function __init__()
                   cfunction(randexp,Float64,()))
 end
 
-    # To be removed when 0.5 support is dropped
```
Comment (tkelman) [inline src/Rmath.jl]: best to do as the comment says

Comment (andreasnoack) [inline src/Rmath.jl]: Done
